---
- name: Installs a package and prints the result
  hosts: dbservers
  become: True
  tasks:
    - name: Install the package
      yum:
        name: git
        state: present
        update_cache: yes
      register: install_result
    - debug: var=install_result
