
---
# tasks file for apache-role
- name: httpd Package
  import_tasks: install-redhat.yml
  when: ansible_os_family|lower == "redhat"
- name: apache2 install
  import_tasks: install-debian.yml
  when: ansible_os_family|lower == "debian"
- name: configure httpd
  import_tasks: configure-redhat.yml
  when: ansible_os_faimly|lower == "redhat"
- name: configure apache2
  import_tasks: configure-debian.yml
  when: ansible_os_family|lower == "debian"

- name: Copy index.html file
  template: src=templates/index.html.j2 dest=/var/www/html/index.html

- name: start and enable httpd
  systemd: name=httpd state=started enabled=true
  when: ansible_os_family|lower == "redhat"

- name: start and enabled apache2
  systemd: name=apache2 state=started enabled=true
  when: ansible_os_family|lower == "debian"
